In [53]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
%matplotlib inline

In [34]:
data= pd.read_csv('Avalanche.csv', delimiter=',')

In [83]:
data

Slope Forest Density  Snow Density  Air Temperature  Wind  Prediction
0       59              H            52              -17    19           2
1       24              L            23               -8    19           0
2       15              H            30                7    19           0
3       27              L            61              -13    25           1
4       34              H             4              -20     7           0
5       34              L            76               -7    40           1
6       34              M            73              -32    27           2
7       34              L             4                3     9           1
8       34              M            44                6     6           0
9       34              L            73              -34    13           2
10      34              M            33               13    35           1
11      34              L            51               -4    35           1
12      34              M            59              -29     8           2
13      34              L            64              -21    10           2
14      34              L            76              -27    38           2
15      34              H             2              -23    33           2
16      75              L            70              -11    36           2
17      36              H            43                2    37           1
18      48              L            55               15    19           1
19      29              M            11              -25    38           0
20      59              H            27              -27     6           1
21      48              M            32                8    40           1
22      17              M            15               -2    36           0
23      18              M            31               -4    35           0
24      60              M            58               15     9           2
25      28              H            70              -11    10           1
26      21              M            70              -27     8           1
27      79              M             2               13    27           2
28      52              H            35              -18    13           2
29      61              H            67              -30     9           1
30      53              L            12                9    16           1
31      63              M            69              -11    30           2
32      52              M             8                3     7           1
33      61              L            17              -11     9           2
34      24              L            57               -8    24           0
35      73              L            11              -26    27           2
36      51              H            69                1    20           1
37      80              L            73               14    35           2
38      69              L            68              -28    14           2
39      65              L            68              -13    12           2
40      24              L            42                8    24           1
41      60              L            74              -25    36           2
42      64              H            52              -14    36           1
43      74              M            27              -25    33           2
44      18              L            21              -11    23           1
45      26              H            12               -8    17           0
46      61              H            42               -7    34           1
47      69              M            29               15    15           2
48      51              M             5                3     7           0
49      36              M            40               -2     7           1
50      65              M            16                0    36           2
51      33              L            10                6    31           1
52      35              H     

In [36]:
data.isnull().any()

Slope              False
Forest Density     False
Snow Density       False
Air Temperature    False
Wind               False
Prediction         False
dtype: bool

In [116]:
y= data['Prediction'].values
y

array([2, 0, 0, 1, 0, 1, 2, 1, 0, 2, 1, 1, 2, 2, 2, 2, 2, 1, 1, 0, 1, 1,
       0, 0, 2, 1, 1, 2, 2, 1, 1, 2, 1, 2, 0, 2, 1, 2, 2, 2, 1, 2, 1, 2,
       1, 0, 1, 2, 0, 1, 2, 1, 0, 1, 1, 0, 0, 0, 2, 2, 1, 0, 0, 1, 0, 1,
       1, 0, 2, 1, 2, 0, 1, 1, 2, 0, 2, 0, 0, 1, 1, 2, 1, 2, 1, 1, 1, 0,
       2, 0, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 0, 0, 1, 0, 1, 2, 1, 0, 2, 1,
       1, 2, 2, 2, 2, 2, 1, 1, 0, 1, 1, 2, 0, 0, 1, 0, 1, 2, 1, 0, 2, 1,
       1, 2, 2, 2, 2, 2, 1, 1, 0, 1, 1, 1, 0, 0, 0, 2, 2, 1, 0, 0, 1, 0,
       1, 1, 0, 2, 1, 2, 0, 1, 1, 2, 0, 2, 2, 1, 0, 0, 1, 0, 1, 1, 0, 2,
       1, 2, 0, 2, 2, 1, 0, 0, 1, 0, 1, 1, 0, 2, 1, 2, 0, 0, 1, 0, 1, 2,
       1, 0, 2, 1, 1, 2], dtype=int64)

In [117]:
x= data.drop('Prediction', axis=1)

In [118]:
x.head()

Slope Forest Density  Snow Density  Air Temperature  Wind
0     59              H            52              -17    19
1     24              L            23               -8    19
2     15              H            30                7    19
3     27              L            61              -13    25
4     34              H             4              -20     7

In [119]:
X= x.values
X

array([[59, 'H', 52, -17, 19],
       [24, 'L', 23, -8, 19],
       [15, 'H', 30, 7, 19],
       ...,
       [34, 'M', 33, 13, 35],
       [34, 'L', 51, -4, 35],
       [34, 'M', 59, -29, 8]], dtype=object)

In [120]:
ct= ColumnTransformer([("oh",OneHotEncoder(),[1])],remainder= "passthrough")

In [121]:
X=ct.fit_transform(X)

In [122]:
X= X[:,1:]
X

array([[0.0, 0.0, 59, 52, -17, 19],
       [1.0, 0.0, 24, 23, -8, 19],
       [0.0, 0.0, 15, 30, 7, 19],
       ...,
       [0.0, 1.0, 34, 33, 13, 35],
       [1.0, 0.0, 34, 51, -4, 35],
       [0.0, 1.0, 34, 59, -29, 8]], dtype=object)

In [123]:
X1=X[:,0:2]
X1

array([[0.0, 0.0],
       [1.0, 0.0],
       [0.0, 0.0],
       [1.0, 0.0],
       [0.0, 0.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [0.0, 0.0],
       [1.0, 0.0],
       [0.0, 0.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 0.0],
       [0.0, 0.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [0.0, 0.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [0.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 0.0],
       [0.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0,

In [124]:
#normalising the data
sc= StandardScaler()
X= sc.fit_transform(X[:,2:6])
X

array([[ 7.88253927e-01,  5.09563173e-01, -5.14512437e-01,
        -2.89456573e-01],
       [-1.05401548e+00, -6.77745111e-01,  8.60246477e-02,
        -2.89456573e-01],
       [-1.52774190e+00, -3.91153456e-01,  1.08691979e+00,
        -2.89456573e-01],
       [-8.96106674e-01,  8.78038158e-01, -2.47607066e-01,
         2.19587745e-01],
       [-5.27652792e-01, -1.45563675e+00, -7.14691465e-01,
        -1.30754521e+00],
       [-5.27652792e-01,  1.49216313e+00,  1.52750990e-01,
         1.49219854e+00],
       [-5.27652792e-01,  1.36933814e+00, -1.51540758e+00,
         3.89269184e-01],
       [-5.27652792e-01, -1.45563675e+00,  8.20014418e-01,
        -1.13786377e+00],
       [-5.27652792e-01,  1.82029854e-01,  1.02019345e+00,
        -1.39238593e+00],
       [-5.27652792e-01,  1.36933814e+00, -1.64886026e+00,
        -7.98500891e-01],
       [-5.27652792e-01, -2.68328461e-01,  1.48727784e+00,
         1.06799494e+00],
       [-5.27652792e-01,  4.68621508e-01,  3.52930019e-01,
      

In [125]:
X= np.hstack((X1,X))
X

array([[0.0, 0.0, 0.788253926739632, 0.5095631733587376,
        -0.5145124367821234, -0.2894565729727524],
       [1.0, 0.0, -1.0540154797811445, -0.6777451108438192,
        0.08602464772644529, -0.2894565729727524],
       [0.0, 0.0, -1.5277418986007727, -0.39115345603630547,
        1.0869197885740598, -0.2894565729727524],
       ...,
       [0.0, 1.0, -0.5276527922037798, -0.2683284611187996,
        1.4872778449131057, 1.067994941658087],
       [1.0, 0.0, -0.5276527922037798, 0.46862150838623556,
        0.3529300186191425, 1.067994941658087],
       [0.0, 1.0, -0.5276527922037798, 0.7961548281662512,
        -1.3152285494602152, -1.2227044892814545]], dtype=object)

In [137]:
##spliting into train and test data
x_train, x_test, y_train, y_test= train_test_split(X,y, train_size=0.8, random_state=0)

### Building the model

In [138]:
#decision tree
avalanche_dt= DecisionTreeClassifier(criterion= 'entropy', random_state=0)
avalanche_dt.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [139]:
y_pred_dt= avalanche_dt.predict(x_test)

In [140]:
accuracy_score(y_test, y_pred_dt)

0.8292682926829268

In [141]:
confusion_matrix(y_test, y_pred_dt)

array([[13,  0,  0],
       [ 5, 14,  0],
       [ 0,  2,  7]], dtype=int64)

In [142]:
y_val= avalanche_dt.predict(x_train)
accuracy_score(y_train, y_val)

1.0

In [143]:
#random forest
rf= RandomForestClassifier(n_estimators=10, criterion= 'entropy', random_state=0)
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [144]:
y_pred_rf= rf.predict(x_test)

In [145]:
accuracy_score(y_test, y_pred_rf)

0.8292682926829268

In [146]:
confusion_matrix(y_test, y_pred_rf)

array([[12,  0,  1],
       [ 4, 15,  0],
       [ 0,  2,  7]], dtype=int64)

In [147]:
y_val2= rf.predict(x_train)
accuracy_score(y_train, y_val2)

0.9815950920245399